### ISSUE TITLE
Having trouble installing promo modal

### ISSUE THREAD

**Issue by div-cowboy** [jonsadka/gatsby-plugin-affirm#2]
I'm trying to access the Affirm promo modal in my Gatsby app, but it's not appearing.

I installed the package, and my config is attached, but I'm not seeing anything when I add:

```
<p
                        class="affirm-as-low-as"
                        data-page-type="product"
                        data-amount="300"
                    ></p>
```

Please let me know what I'm missing

![Screen Shot 2021-01-05 at 11 45 05 AM](https://user-images.githubusercontent.com/6291624/103673555-b99abf00-4f4b-11eb-9800-f98cb38ef668.png)

**Comment by jonsadka** [comment]
Hi @iamkratos,

Im guessing because the amount specified is too low. Affirm uses the `amount` as pennies and $3 is probably too low for them to offer terms. Try setting something like `50000` for the amount
